### ISSUE TITLE
pip version is broken

### ISSUE THREAD

**Issue by grburgess** [me-manu/ebltable#2]
Hi Manuel, 

We had some issues in astromodels because the pypi version of ebltable is broken in py3. I cloned the repo to fix it and discovered that the fix is already there and perhaps you have not pushed to the pypi server yet. Is there anyway you could do this?

The error we are getting is about the tabs being inconsistent in some of the files.

**Comment by me-manu** [comment]
Hi Michael, 

Yes, indeed, I already fixed the tab indent problems for python 3 but didn't push the changes to pypi yet. I hope I'll get to it this week!

**Comment by grburgess** [comment]
Thanks!

**Comment by me-manu** [comment]
I just uploaded the new version 0.2 to pypi. Let me know if there are problems.
