### ISSUE TITLE
Improve the API for reading in own EBL model

### ISSUE THREAD

**Issue by chopra010** [me-manu/ebltable#6]
In the version 0.5 of ebltable, after reading in own model of EBL using readascii method, the self._model is not set and it's initialized to None. Currently an additional step of assigning ebl._model = "my_model" is required for it to work.

**Comment by me-manu** [comment]
Thank you @chopra010 for noticing this. This should be fix in version 0.5.2 now. When you initialize the class with the `readascii` function, you can now supply a name for the model through the `model_name=...` keyword. Please reopen the issue if the problem persists.
