### ISSUE TITLE
CUBA EBL model units

### ISSUE THREAD

**Issue by saraporrasbedmar** [me-manu/ebltable#8]
The CUBA EBL model is not in comoving units.

Proposed solution in line 174, in 'ebl_from_model.py':
nuInu /= ((1. + z)**3.)[np.newaxis, :]

**Comment by me-manu** [comment]
This should be fixed in PR #10 which is included in the latest version 0.6.2. I'm closing this issue now, but feel free to re-open if there's still an issue.
