### ISSUE TITLE
scipy.integrate.simps

### ISSUE THREAD

**Issue by remi-adam** [me-manu/ebltable#9]
It seems that scipy.integrate.simps was replaced by scipy.integrate.simpson in  the last versions of scipy. 

In tau_from_model.py, with the new version, lines 4 should now read: 
from scipy.integrate import simpson as simps

**Comment by me-manu** [comment]
Thanks a lot @remi-adam ! This should be fixed in PR #10 which is included in the latest version 0.6.2. I'm closing this issue now, but feel free to re-open if there's still an issue.
